[package]
name = "create_xmf"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdf5 = "0.7.1"
failure = "0.1.8"
ndarray = "0.14"